name: Build Flutter APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'

      - name: Install dependencies
        run: flutter pub get

      - name: Ensure android project exists (create minimal if missing)
        run: |
          if [ ! -d "android" ]; then
            echo "No android/ folder found. Running flutter create to generate android skeleton."
            flutter create .
          else
            echo "android/ exists"
          fi

      - name: Build release APK
        run: flutter build apk --release

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: pingpong-over-app
          path: build/app/outputs/flutter-apk/app-release.apk